runtime: nodejs14
handlers:
# Serve all static files with url ending with a file extentsion
-url: /(.*\..+)$
 static_files: build/\1
 upload: /(.*\..+)$
# Catch all handler to index.html
-url: /.*
 static_files: build/index.html
 update: build.index.html