# runtime: nodejs12
# handlers:
# # Serve all static files with url ending with a file extension
# - url: /(.*\..+)$
#   static_files: build/\1
#   upload: build/(.*\..+)$
# # Catch all handler to index.html
# - url: /.*
#   static_files: build/index.html
#   upload: build/index.html

steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
# Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'